/*
  C-file generated by Bin2C
  Compiled:    Feb 27 2020 at 09:43:26

  Copyright (C) 2018
  Segger Microcontroller GmbH
  www.segger.com

  The Embedded Experts
*/

const unsigned char acAPPW_Language_0[18UL + 1] = {
  0x42, 0x75, 0x74, 0x74, 0x6F, 0x6E, 0x0A, 0x4F, 0x70, 0x65, 0x6E, 0x0A, 0x43, 0x6C, 0x6F, 0x73, 0x65, 0x0A, 0x00
};

/*************************** End of file ****************************/
