/*
  C-file generated by Bin2C
  Compiled:    Feb 27 2020 at 09:43:26

  Copyright (C) 2018
  Segger Microcontroller GmbH
  www.segger.com

  The Embedded Experts
*/

const unsigned char acAPPW_Language_1[16UL + 1] = {
  0xE6, 0x8C, 0x89, 0xE9, 0x92, 0xAE, 0x0A, 0xE5, 0xBC, 0x80, 0x0A, 0xE5, 0x85, 0xB3, 0x0A, 0x0A, 0x00
};

/*************************** End of file ****************************/
